### ISSUE TITLE
The demon does not find peers

### ISSUE THREAD

**Issue by kr1z1s** [NextSmartChain/next-binary#1]
Hello

demon does not find peers

Please tell me working peer addresses.

**Comment by dcnl1980** [comment]
Go the the console and put this:

admin.addPeer('enode://50c26e68d5b834ee1f0b66ea335c6d86b398670b504ee7482c07606440eec05b6a7bf144e0340790a2220e0efc1a5e81ec1531cb472341dfb80a17cb9d080e82@95.217.231.40:5120')

**Comment by kr1z1s** [comment]
admin.addPeer('enode://50c26e68d5b834ee1f0b66ea335c6d86b398670b504ee7482c07606440eec05b6a7bf144e0340790a2220e0efc1a5e81ec1531cb472341dfb80a17cb9d080e82@95.217.231.40:5120')

not work

please give correct peer

**Comment by aradabir007** [comment]
Try this;
```
enode://50c26e68d5b834ee1f0b66ea335c6d86b398670b504ee7482c07606440eec05b6a7bf144e0340790a2220e0efc1a5e81ec1531cb472341dfb80a17cb9d080e82@168.119.2.101:6001
```

**Comment by kr1z1s** [comment]
> Try this;
> 
> ```
> enode://50c26e68d5b834ee1f0b66ea335c6d86b398670b504ee7482c07606440eec05b6a7bf144e0340790a2220e0efc1a5e81ec1531cb472341dfb80a17cb9d080e82@168.119.2.101:6001
> ```

thank but not work.
