### ISSUE TITLE
peer not connect

### ISSUE THREAD

**Issue by kr1z1s** [NextSmartChain/next-binary#2]
Go the the console and put this:

admin.addPeer('enode://50c26e68d5b834ee1f0b66ea335c6d86b398670b504ee7482c07606440eec05b6a7bf144e0340790a2220e0efc1a5e81ec1531cb472341dfb80a17cb9d080e82@95.217.231.40:5120')

this is not work now

please give correct peers

_Originally posted by @dcnl1980 in https://github.com/NextSmartChain/next-binary/issues/1#issuecomment-1664268127_

**Comment by aradabir007** [comment]
Try this;
```
enode://50c26e68d5b834ee1f0b66ea335c6d86b398670b504ee7482c07606440eec05b6a7bf144e0340790a2220e0efc1a5e81ec1531cb472341dfb80a17cb9d080e82@168.119.2.101:6001
```

**Comment by dcnl1980** [comment]
enode://aac81830e98def8d0133f552bbe07241480634bd0475a9c05315618268e90febb4dd4109351f06cf019976c5e52d92f9fc68af0a90e2c21251db8b113441873b@95.179.128.108:9920

**Comment by dcnl1980** [comment]
Thanks for this issue, it will be closed now, since it is solved.
